blank_issues_enabled: false
contact_links:
    - name: 💬 Diskusi & Tanya Jawab
      url: https://github.com/proyek-2m/portopro/discussions
      about: Untuk pertanyaan umum, ide, atau diskusi yang bukan bug/fitur.
    - name: 🙌 Panduan Kontribusi
      url: https://github.com/proyek-2m/portopro/blob/main/CONTRIBUTING.md
      about: Pelajari cara berkontribusi ke proyek ini.
